### PUT /school/:id/news/:newsId
# 학교 소식 삭제 API

# Request Parameter (path)
# - id: 학교 고유 아이디
  # - string(mandatory)
# - newsId: 학교 소식 아이디
  # - string(mandatory)

@schoolId = 82514c58-b393-4169-9791-7343672e034e
@newsId = 79e9412b-386f-4885-a95d-42d59976f096

DELETE http://localhost:3000/school/{{schoolId}}/news/{{newsId}}
Content-Type: application/json

# Response Example
# {
#   "success": true,
#   "data": {
#     "affectedId": "35ebb5a3-1cb1-447a-b67f-b9c333fd9fad"
#   }
# }