### POST /school/:id/news
# 학교 소식 생성 API

# Request Parameter (path)
# - id: 학교 고유 아이디
  # - string(mandatory)

# Request Parameter (application/json body)
# - title: 뉴스 제목
  # - string(mandatory)

# - content: 뉴스 본문
  # - string(mandatory)

@schoolId = 4bf1cf89-7979-4a4e-aac5-289343699337

@title = "뉴스 제목입니다."
@content = "뉴스 본문입니다."

POST http://localhost:3000/school/{{schoolId}}/news
Content-Type: application/json

{
    "title": {{title}},
    "content": {{content}}
}

# Response Example
# {
#   "success": true,
#   "data": {
#     "affectedId": "35ebb5a3-1cb1-447a-b67f-b9c333fd9fad"
#   }
# }