### PUT /school/:id/news/:newsId
# 학교 소식 수정 API

# Request Parameter (path)
# - id: 학교 고유 아이디
  # - string(mandatory)
# - newsId: 학교 소식 아이디
  # - string(mandatory)

# Request Parameter (application/json body)
# - title: 뉴스 제목
  # - string(mandatory)

# - content: 뉴스 본문
  # - string(mandatory)

@schoolId = 82514c58-b393-4169-9791-7343672e034e
@newsId = 79e9412b-386f-4885-a95d-42d59976f096

@title = "뉴스 제목입니다."
@content = "뉴스 본문입니다."

PUT http://localhost:3000/school/{{schoolId}}/news/{{newsId}}
Content-Type: application/json

{
    "title": {{title}},
    "content": {{content}}
}

# Response Example
# {
#   "success": true,
#   "data": {
#     "affectedId": "35ebb5a3-1cb1-447a-b67f-b9c333fd9fad"
#   }
# }