### POST /student/:id/school/:schoolId/subscription
# 학교 구독 API

# Request Parameter (path)
# - id: 학생 아이디
  # - string(mandatory)
# - schoolId: 학교 고유 아이디
  # - string(mandatory)

@id = "5f4a514d-1b7b-4b1d-8f8f-2f1b7b4b1d8f"
@schoolId = "5f4a514d-1b7b-4b1d-8f8f-2f1b7b4b1d8f"

POST http://localhost:3000/student/{{id}}/school/{{schoolId}}/subscription
Content-Type: application/json

# Response Example
# {
#   "success": true,
#   "data": {
#     "affectedId": "35ebb5a3-1cb1-447a-b67f-b9c333fd9fad"
#   }
# }